services:
  db:
    image: postgres:16
    container_name: calenderapp-api
    restart: unless-stopped
    environment:
      POSTGRES_DB: CalenderAppDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123password
    volumes:

- db_data:/var/lib/postgresql/data
  ports:
  - "5433:5432"

volumes:
  db_data:
